Hw2, Головастенко Александр
TheGeode/Linux-basics-2020 pull request #2
Opened 2020-09-17 13:21 UTC by TheGeode

2020-09-20 18:23 UTC, sloboegen98 requested changes
Поправь, пожалуйста, замечания, их немного.

2020-09-20 18:23 UTC, sloboegen98 commented on seminar02/task03/task03.sh
> +kill $(ps -e | grep tail | awk '{print $1}')
Оп, оп, stackoverflow:) Нужно было почитать чуть подольше эту страничку, там что-то написано про ```grep -v grep```. Нужно понять зачем это и поправить.

2020-09-20 18:23 UTC, sloboegen98 commented on seminar02/task08/task08.sh
> +cat hamlet.txt | sed -e "s/ /\n/g" | grep -i "the"| sed -e "s/[[:punct:]]\+//g" | awk '{print "|" length "|"}' | grep "|3|" | wc -l
Прокомментирую, что все что нужно умеет ```grep```, остальное использовать не надо. Выглядит очень страшно.

2020-09-20 18:23 UTC, sloboegen98 commented on seminar02/task09/task09.sh
> +grep "@" emails.txt | grep "\."
Хотелось бы увидеть регулярное выражение, а не просто "@"...

2020-09-20 18:36 UTC, TheGeode commented on seminar02/task03/task03.sh
> +kill $(ps -e | grep tail | awk '{print $1}')
Никаких стаковерфловов для этого задания не использовалось, так что я не знаю что за страничка имеется ввиду

2020-09-20 18:48 UTC, sloboegen98 commented on seminar02/task03/task03.sh
> +kill $(ps -e | grep tail | awk '{print $1}')
Извини, просто там точно такая же команда, я и подумал, что оттуда. Но в общем, [вот](https://stackoverflow.com/questions/8653921/how-to-give-arguments-to-kill-via-pipe)

2020-09-20 20:42 UTC, TheGeode commented on seminar02/task03/task03.sh
> +kill $(ps -e | grep tail | awk '{print $1}')
Интересно... Команда действительно такая же, но я абсолютно точно помню что использовал только логику и команду man

2020-09-20 20:53 UTC, sloboegen98 commented on seminar02/task03/task03.sh
> +kill $(ps -e | grep tail | awk '{print $1}')
Да, в целом, это неважно и нестрашно. Просто тут есть небольшая проблема, которую ```grep -v grep``` может решить.

2020-09-23 13:20 UTC, TheGeode commented on seminar02/task08/task08.sh
> +cat hamlet.txt | sed -e "s/ /\n/g" | grep -i "the"| sed -e "s/[[:punct:]]\+//g" | awk '{print "|" length "|"}' | grep "|3|" | wc -l
Проблема с программой тестирования -- она говорит, что я ничего не вывожу, когда я что-то вывожу

2020-09-23 13:25 UTC, TheGeode commented on seminar02/task08/task08.sh
> +cat hamlet.txt | sed -e "s/ /\n/g" | grep -i "the"| sed -e "s/[[:punct:]]\+//g" | awk '{print "|" length "|"}' | grep "|3|" | wc -l
и да, кстати, предыдущая реализация даже выводиле неправильный ответ, поскольку не засчитывала слово the в строке "them to their trial-the bubbles are out" из-за слипшегося тире

2020-09-23 15:00 UTC, sloboegen98 commented on seminar02/task08/task08.sh
> +cat hamlet.txt | sed -e "s/ /\n/g" | grep -i "the"| sed -e "s/[[:punct:]]\+//g" | awk '{print "|" length "|"}' | grep "|3|" | wc -l
Да, я вчера тоже обнаружил, что на одно слово больше выводится, но пока еще не успел поправить

2020-09-23 15:05 UTC, sloboegen98 commented on seminar02/task03/task03.sh
> +kill $(ps -e | grep tail | awk '{print $1}')
Можно, кстати, здесь еще красивый пайплан сделать

2020-09-23 15:05 UTC, sloboegen98 commented
Все зачтено

2020-09-23 15:06 UTC, sloboegen98 approved these changes

2020-09-23 15:06 UTC, closed without merging